version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"

  python-server:
    build:
      context: .
      dockerfile: servers/python/Dockerfile.python
    restart: always
    ports:
      - "${PYTHON_SERVER_PORT}:${PYTHON_SERVER_PORT}"

