FROM node:12

ENV DIR=backend

ENV PROTOS_DIR=protos

WORKDIR /leetcode/${DIR}

COPY $DIR/package*.json ./

RUN npm install

COPY ${DIR}/. ./

COPY .env ../

COPY ${PROTOS_DIR} ../${PROTOS_DIR}/

RUN npm run build-proto

EXPOSE $BACKEND_PORT

CMD ["npm", "start"]