FROM node:12-slim

ENV DIR=backend

WORKDIR /leetcode/${DIR}

COPY $DIR/package*.json ./

RUN npm install

ENV PROTOS_DIR=protos

COPY ${PROTOS_DIR} ../${PROTOS_DIR}/

COPY ${DIR}/build-proto.sh .

RUN ls && echo "\n" && ls ..

RUN npm run build-proto-sh

COPY ${DIR}/. ./

COPY .env ../

EXPOSE $BACKEND_PORT

CMD ["npm", "start"]