# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/solution.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/solution.proto\x1a\x1cgoogle/protobuf/struct.proto\"Z\n\nSubmission\x12\x11\n\tproblemId\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12)\n\x08testcase\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"R\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bnoOfSuccess\x18\x02 \x01(\x03\x12\x12\n\nnoOfFailed\x18\x03 \x01(\x03\x12\x0e\n\x06output\x18\x04 \x01(\t22\n\rProblemSolver\x12!\n\tGetResult\x12\x0b.Submission\x1a\x07.Resultb\x06proto3')



_SUBMISSION = DESCRIPTOR.message_types_by_name['Submission']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Submission = _reflection.GeneratedProtocolMessageType('Submission', (_message.Message,), {
  'DESCRIPTOR' : _SUBMISSION,
  '__module__' : 'protos.solution_pb2'
  # @@protoc_insertion_point(class_scope:Submission)
  })
_sym_db.RegisterMessage(Submission)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'protos.solution_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

_PROBLEMSOLVER = DESCRIPTOR.services_by_name['ProblemSolver']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBMISSION._serialized_start=55
  _SUBMISSION._serialized_end=145
  _RESULT._serialized_start=147
  _RESULT._serialized_end=229
  _PROBLEMSOLVER._serialized_start=231
  _PROBLEMSOLVER._serialized_end=281
# @@protoc_insertion_point(module_scope)
